version: '3.6'

services:
  geth:
    image: ethereum/client-go:stable
    restart: always
    command: |
      --syncmode=full
      --rinkeby
      --rpc
      --rpcaddr=0.0.0.0
      --rpcport=8545
      --port=30303
      --rpcapi="db,personal,eth,net,web3"
      --rpccorsdomain="*"
      --rpcvhosts="*"
    volumes:
      - ../data/geth:/root/.ethereum/
    expose:
      - "8545"
      - "30303"
    labels:
      traefik.enable: true
      traefik.frontend.rule: 'Host: eth.app.local'
      traefik.port: 8545
