version: '3.6'

services:
  frontend:
    image: "${FRONTEND_IMAGE}"
    volumes:
      - ../config/frontend/env.js:/home/node/public/env.js
    labels:
      traefik.enable: true
      traefik.frontend.rule: "PathPrefix:/;Host:www.${APP_DOMAIN}"
      traefik.port: 3000

  tower:
    image: "${TOWER_IMAGE}"
    volumes:
      - ../config/frontend/tower.js:/home/app/env.js
    labels:
      traefik.enable: true
      traefik.frontend.rule: "PathPrefix:/tower;Host:www.${APP_DOMAIN}"
      traefik.port: 8080

